# Generated by Django 5.2 on 2025-07-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_checker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisstep",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="analysisstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("topic_analysis", "Topic Analysis"),
                    ("source_search", "Source Search"),
                    ("content_extraction", "Content Extraction"),
                    ("source_evaluation", "Source Evaluation"),
                    ("final_verdict", "Final Verdict"),
                    ("initial_web_search", "Initial Web Search"),
                    ("deeper_exploration", "Deeper Exploration"),
                    ("source_credibility_evaluation", "Source Credibility Evaluation"),
                    ("final_conclusion", "Final Conclusion"),
                    ("search", "Legacy Search"),
                ],
                max_length=30,
            ),
        ),
    ]
