# Generated by Django 5.2 on 2025-07-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fact_checker", "0002_analysisstep_summary_alter_analysisstep_step_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="factchecksession",
            name="mode",
            field=models.CharField(
                choices=[("fact_check", "Fact Check"), ("research", "Research")],
                default="fact_check",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="analysisstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("topic_analysis", "Topic Analysis"),
                    ("source_search", "Source Search"),
                    ("content_extraction", "Content Extraction"),
                    ("source_evaluation", "Source Evaluation"),
                    ("final_verdict", "Final Verdict"),
                    ("initial_web_search", "Initial Web Search"),
                    ("deeper_exploration", "Deeper Exploration"),
                    ("source_credibility_evaluation", "Source Credibility Evaluation"),
                    ("final_conclusion", "Final Conclusion"),
                    ("research_understanding", "Research Understanding"),
                    ("general_research", "General Research"),
                    ("specific_research", "Specific Research"),
                    ("research_report", "Research Report"),
                    ("search", "Legacy Search"),
                ],
                max_length=30,
            ),
        ),
    ]
